# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/developer/Downloads/Alert_Manager/alertManager/Parts_Store/Utilities

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/developer/Downloads/Alert_Manager/alertManager/Parts_Store/Utilities

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/developer/Downloads/Alert_Manager/alertManager/Parts_Store/Utilities/CMakeFiles /home/developer/Downloads/Alert_Manager/alertManager/Parts_Store/Utilities/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/developer/Downloads/Alert_Manager/alertManager/Parts_Store/Utilities/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Utilities

# Build rule for target.
Utilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Utilities
.PHONY : Utilities

# fast build rule for target.
Utilities/fast:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/build
.PHONY : Utilities/fast

src/Utilities.o: src/Utilities.cpp.o

.PHONY : src/Utilities.o

# target to build an object file
src/Utilities.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/Utilities.cpp.o
.PHONY : src/Utilities.cpp.o

src/Utilities.i: src/Utilities.cpp.i

.PHONY : src/Utilities.i

# target to preprocess a source file
src/Utilities.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/Utilities.cpp.i
.PHONY : src/Utilities.cpp.i

src/Utilities.s: src/Utilities.cpp.s

.PHONY : src/Utilities.s

# target to generate assembly for a file
src/Utilities.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/Utilities.cpp.s
.PHONY : src/Utilities.cpp.s

src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.o: src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.o

.PHONY : src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.o

# target to build an object file
src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.o
.PHONY : src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.o

src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.i: src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.i

.PHONY : src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.i

# target to preprocess a source file
src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.i
.PHONY : src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.i

src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.s: src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.s

.PHONY : src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.s

# target to generate assembly for a file
src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.s
.PHONY : src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.cpp.s

src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.o: src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.o

.PHONY : src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.o

# target to build an object file
src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.o
.PHONY : src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.o

src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.i: src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.i

.PHONY : src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.i

# target to preprocess a source file
src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.i
.PHONY : src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.i

src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.s: src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.s

.PHONY : src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.s

# target to generate assembly for a file
src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.s
.PHONY : src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.cpp.s

src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.o: src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.o

.PHONY : src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.o

# target to build an object file
src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.o
.PHONY : src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.o

src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.i: src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.i

.PHONY : src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.i

# target to preprocess a source file
src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.i
.PHONY : src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.i

src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.s: src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.s

.PHONY : src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.s

# target to generate assembly for a file
src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.s
.PHONY : src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.cpp.s

src/impl/iDirectory/GoogleMock/MockDirectory.o: src/impl/iDirectory/GoogleMock/MockDirectory.cpp.o

.PHONY : src/impl/iDirectory/GoogleMock/MockDirectory.o

# target to build an object file
src/impl/iDirectory/GoogleMock/MockDirectory.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/GoogleMock/MockDirectory.cpp.o
.PHONY : src/impl/iDirectory/GoogleMock/MockDirectory.cpp.o

src/impl/iDirectory/GoogleMock/MockDirectory.i: src/impl/iDirectory/GoogleMock/MockDirectory.cpp.i

.PHONY : src/impl/iDirectory/GoogleMock/MockDirectory.i

# target to preprocess a source file
src/impl/iDirectory/GoogleMock/MockDirectory.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/GoogleMock/MockDirectory.cpp.i
.PHONY : src/impl/iDirectory/GoogleMock/MockDirectory.cpp.i

src/impl/iDirectory/GoogleMock/MockDirectory.s: src/impl/iDirectory/GoogleMock/MockDirectory.cpp.s

.PHONY : src/impl/iDirectory/GoogleMock/MockDirectory.s

# target to generate assembly for a file
src/impl/iDirectory/GoogleMock/MockDirectory.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/GoogleMock/MockDirectory.cpp.s
.PHONY : src/impl/iDirectory/GoogleMock/MockDirectory.cpp.s

src/impl/iDirectory/Qt/QtDirectory.o: src/impl/iDirectory/Qt/QtDirectory.cpp.o

.PHONY : src/impl/iDirectory/Qt/QtDirectory.o

# target to build an object file
src/impl/iDirectory/Qt/QtDirectory.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/Qt/QtDirectory.cpp.o
.PHONY : src/impl/iDirectory/Qt/QtDirectory.cpp.o

src/impl/iDirectory/Qt/QtDirectory.i: src/impl/iDirectory/Qt/QtDirectory.cpp.i

.PHONY : src/impl/iDirectory/Qt/QtDirectory.i

# target to preprocess a source file
src/impl/iDirectory/Qt/QtDirectory.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/Qt/QtDirectory.cpp.i
.PHONY : src/impl/iDirectory/Qt/QtDirectory.cpp.i

src/impl/iDirectory/Qt/QtDirectory.s: src/impl/iDirectory/Qt/QtDirectory.cpp.s

.PHONY : src/impl/iDirectory/Qt/QtDirectory.s

# target to generate assembly for a file
src/impl/iDirectory/Qt/QtDirectory.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/Qt/QtDirectory.cpp.s
.PHONY : src/impl/iDirectory/Qt/QtDirectory.cpp.s

src/impl/iDirectory/Unix/UnixDirectory.o: src/impl/iDirectory/Unix/UnixDirectory.cpp.o

.PHONY : src/impl/iDirectory/Unix/UnixDirectory.o

# target to build an object file
src/impl/iDirectory/Unix/UnixDirectory.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/Unix/UnixDirectory.cpp.o
.PHONY : src/impl/iDirectory/Unix/UnixDirectory.cpp.o

src/impl/iDirectory/Unix/UnixDirectory.i: src/impl/iDirectory/Unix/UnixDirectory.cpp.i

.PHONY : src/impl/iDirectory/Unix/UnixDirectory.i

# target to preprocess a source file
src/impl/iDirectory/Unix/UnixDirectory.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/Unix/UnixDirectory.cpp.i
.PHONY : src/impl/iDirectory/Unix/UnixDirectory.cpp.i

src/impl/iDirectory/Unix/UnixDirectory.s: src/impl/iDirectory/Unix/UnixDirectory.cpp.s

.PHONY : src/impl/iDirectory/Unix/UnixDirectory.s

# target to generate assembly for a file
src/impl/iDirectory/Unix/UnixDirectory.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iDirectory/Unix/UnixDirectory.cpp.s
.PHONY : src/impl/iDirectory/Unix/UnixDirectory.cpp.s

src/impl/iLocation/locManagerGPS.o: src/impl/iLocation/locManagerGPS.cpp.o

.PHONY : src/impl/iLocation/locManagerGPS.o

# target to build an object file
src/impl/iLocation/locManagerGPS.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iLocation/locManagerGPS.cpp.o
.PHONY : src/impl/iLocation/locManagerGPS.cpp.o

src/impl/iLocation/locManagerGPS.i: src/impl/iLocation/locManagerGPS.cpp.i

.PHONY : src/impl/iLocation/locManagerGPS.i

# target to preprocess a source file
src/impl/iLocation/locManagerGPS.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iLocation/locManagerGPS.cpp.i
.PHONY : src/impl/iLocation/locManagerGPS.cpp.i

src/impl/iLocation/locManagerGPS.s: src/impl/iLocation/locManagerGPS.cpp.s

.PHONY : src/impl/iLocation/locManagerGPS.s

# target to generate assembly for a file
src/impl/iLocation/locManagerGPS.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iLocation/locManagerGPS.cpp.s
.PHONY : src/impl/iLocation/locManagerGPS.cpp.s

src/impl/iMutex/Appareo/AppareoMutex.o: src/impl/iMutex/Appareo/AppareoMutex.cpp.o

.PHONY : src/impl/iMutex/Appareo/AppareoMutex.o

# target to build an object file
src/impl/iMutex/Appareo/AppareoMutex.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Appareo/AppareoMutex.cpp.o
.PHONY : src/impl/iMutex/Appareo/AppareoMutex.cpp.o

src/impl/iMutex/Appareo/AppareoMutex.i: src/impl/iMutex/Appareo/AppareoMutex.cpp.i

.PHONY : src/impl/iMutex/Appareo/AppareoMutex.i

# target to preprocess a source file
src/impl/iMutex/Appareo/AppareoMutex.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Appareo/AppareoMutex.cpp.i
.PHONY : src/impl/iMutex/Appareo/AppareoMutex.cpp.i

src/impl/iMutex/Appareo/AppareoMutex.s: src/impl/iMutex/Appareo/AppareoMutex.cpp.s

.PHONY : src/impl/iMutex/Appareo/AppareoMutex.s

# target to generate assembly for a file
src/impl/iMutex/Appareo/AppareoMutex.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Appareo/AppareoMutex.cpp.s
.PHONY : src/impl/iMutex/Appareo/AppareoMutex.cpp.s

src/impl/iMutex/GoogleMock/MockMutex.o: src/impl/iMutex/GoogleMock/MockMutex.cpp.o

.PHONY : src/impl/iMutex/GoogleMock/MockMutex.o

# target to build an object file
src/impl/iMutex/GoogleMock/MockMutex.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/GoogleMock/MockMutex.cpp.o
.PHONY : src/impl/iMutex/GoogleMock/MockMutex.cpp.o

src/impl/iMutex/GoogleMock/MockMutex.i: src/impl/iMutex/GoogleMock/MockMutex.cpp.i

.PHONY : src/impl/iMutex/GoogleMock/MockMutex.i

# target to preprocess a source file
src/impl/iMutex/GoogleMock/MockMutex.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/GoogleMock/MockMutex.cpp.i
.PHONY : src/impl/iMutex/GoogleMock/MockMutex.cpp.i

src/impl/iMutex/GoogleMock/MockMutex.s: src/impl/iMutex/GoogleMock/MockMutex.cpp.s

.PHONY : src/impl/iMutex/GoogleMock/MockMutex.s

# target to generate assembly for a file
src/impl/iMutex/GoogleMock/MockMutex.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/GoogleMock/MockMutex.cpp.s
.PHONY : src/impl/iMutex/GoogleMock/MockMutex.cpp.s

src/impl/iMutex/Posix/PosixMutex.o: src/impl/iMutex/Posix/PosixMutex.cpp.o

.PHONY : src/impl/iMutex/Posix/PosixMutex.o

# target to build an object file
src/impl/iMutex/Posix/PosixMutex.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Posix/PosixMutex.cpp.o
.PHONY : src/impl/iMutex/Posix/PosixMutex.cpp.o

src/impl/iMutex/Posix/PosixMutex.i: src/impl/iMutex/Posix/PosixMutex.cpp.i

.PHONY : src/impl/iMutex/Posix/PosixMutex.i

# target to preprocess a source file
src/impl/iMutex/Posix/PosixMutex.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Posix/PosixMutex.cpp.i
.PHONY : src/impl/iMutex/Posix/PosixMutex.cpp.i

src/impl/iMutex/Posix/PosixMutex.s: src/impl/iMutex/Posix/PosixMutex.cpp.s

.PHONY : src/impl/iMutex/Posix/PosixMutex.s

# target to generate assembly for a file
src/impl/iMutex/Posix/PosixMutex.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Posix/PosixMutex.cpp.s
.PHONY : src/impl/iMutex/Posix/PosixMutex.cpp.s

src/impl/iMutex/Windows/WindowsMutex.o: src/impl/iMutex/Windows/WindowsMutex.cpp.o

.PHONY : src/impl/iMutex/Windows/WindowsMutex.o

# target to build an object file
src/impl/iMutex/Windows/WindowsMutex.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Windows/WindowsMutex.cpp.o
.PHONY : src/impl/iMutex/Windows/WindowsMutex.cpp.o

src/impl/iMutex/Windows/WindowsMutex.i: src/impl/iMutex/Windows/WindowsMutex.cpp.i

.PHONY : src/impl/iMutex/Windows/WindowsMutex.i

# target to preprocess a source file
src/impl/iMutex/Windows/WindowsMutex.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Windows/WindowsMutex.cpp.i
.PHONY : src/impl/iMutex/Windows/WindowsMutex.cpp.i

src/impl/iMutex/Windows/WindowsMutex.s: src/impl/iMutex/Windows/WindowsMutex.cpp.s

.PHONY : src/impl/iMutex/Windows/WindowsMutex.s

# target to generate assembly for a file
src/impl/iMutex/Windows/WindowsMutex.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iMutex/Windows/WindowsMutex.cpp.s
.PHONY : src/impl/iMutex/Windows/WindowsMutex.cpp.s

src/impl/iTCPServer/Gateway/GatewayTCPServer.o: src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.o

.PHONY : src/impl/iTCPServer/Gateway/GatewayTCPServer.o

# target to build an object file
src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.o
.PHONY : src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.o

src/impl/iTCPServer/Gateway/GatewayTCPServer.i: src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.i

.PHONY : src/impl/iTCPServer/Gateway/GatewayTCPServer.i

# target to preprocess a source file
src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.i
.PHONY : src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.i

src/impl/iTCPServer/Gateway/GatewayTCPServer.s: src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.s

.PHONY : src/impl/iTCPServer/Gateway/GatewayTCPServer.s

# target to generate assembly for a file
src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.s
.PHONY : src/impl/iTCPServer/Gateway/GatewayTCPServer.cpp.s

src/impl/iTCPSocket/Gateway/GatewayTCPSocket.o: src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.o

.PHONY : src/impl/iTCPSocket/Gateway/GatewayTCPSocket.o

# target to build an object file
src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.o
.PHONY : src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.o

src/impl/iTCPSocket/Gateway/GatewayTCPSocket.i: src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.i

.PHONY : src/impl/iTCPSocket/Gateway/GatewayTCPSocket.i

# target to preprocess a source file
src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.i
.PHONY : src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.i

src/impl/iTCPSocket/Gateway/GatewayTCPSocket.s: src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.s

.PHONY : src/impl/iTCPSocket/Gateway/GatewayTCPSocket.s

# target to generate assembly for a file
src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.s
.PHONY : src/impl/iTCPSocket/Gateway/GatewayTCPSocket.cpp.s

src/impl/iTCPSocket/GoogleMock/MockTCPSocket.o: src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.o

.PHONY : src/impl/iTCPSocket/GoogleMock/MockTCPSocket.o

# target to build an object file
src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.o
.PHONY : src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.o

src/impl/iTCPSocket/GoogleMock/MockTCPSocket.i: src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.i

.PHONY : src/impl/iTCPSocket/GoogleMock/MockTCPSocket.i

# target to preprocess a source file
src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.i
.PHONY : src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.i

src/impl/iTCPSocket/GoogleMock/MockTCPSocket.s: src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.s

.PHONY : src/impl/iTCPSocket/GoogleMock/MockTCPSocket.s

# target to generate assembly for a file
src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.s
.PHONY : src/impl/iTCPSocket/GoogleMock/MockTCPSocket.cpp.s

src/impl/iThread/Appareo/AppareoThread.o: src/impl/iThread/Appareo/AppareoThread.cpp.o

.PHONY : src/impl/iThread/Appareo/AppareoThread.o

# target to build an object file
src/impl/iThread/Appareo/AppareoThread.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/Appareo/AppareoThread.cpp.o
.PHONY : src/impl/iThread/Appareo/AppareoThread.cpp.o

src/impl/iThread/Appareo/AppareoThread.i: src/impl/iThread/Appareo/AppareoThread.cpp.i

.PHONY : src/impl/iThread/Appareo/AppareoThread.i

# target to preprocess a source file
src/impl/iThread/Appareo/AppareoThread.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/Appareo/AppareoThread.cpp.i
.PHONY : src/impl/iThread/Appareo/AppareoThread.cpp.i

src/impl/iThread/Appareo/AppareoThread.s: src/impl/iThread/Appareo/AppareoThread.cpp.s

.PHONY : src/impl/iThread/Appareo/AppareoThread.s

# target to generate assembly for a file
src/impl/iThread/Appareo/AppareoThread.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/Appareo/AppareoThread.cpp.s
.PHONY : src/impl/iThread/Appareo/AppareoThread.cpp.s

src/impl/iThread/Posix/PosixThread.o: src/impl/iThread/Posix/PosixThread.cpp.o

.PHONY : src/impl/iThread/Posix/PosixThread.o

# target to build an object file
src/impl/iThread/Posix/PosixThread.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/Posix/PosixThread.cpp.o
.PHONY : src/impl/iThread/Posix/PosixThread.cpp.o

src/impl/iThread/Posix/PosixThread.i: src/impl/iThread/Posix/PosixThread.cpp.i

.PHONY : src/impl/iThread/Posix/PosixThread.i

# target to preprocess a source file
src/impl/iThread/Posix/PosixThread.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/Posix/PosixThread.cpp.i
.PHONY : src/impl/iThread/Posix/PosixThread.cpp.i

src/impl/iThread/Posix/PosixThread.s: src/impl/iThread/Posix/PosixThread.cpp.s

.PHONY : src/impl/iThread/Posix/PosixThread.s

# target to generate assembly for a file
src/impl/iThread/Posix/PosixThread.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/Posix/PosixThread.cpp.s
.PHONY : src/impl/iThread/Posix/PosixThread.cpp.s

src/impl/iThread/PosixWindows/PosixThread.o: src/impl/iThread/PosixWindows/PosixThread.cpp.o

.PHONY : src/impl/iThread/PosixWindows/PosixThread.o

# target to build an object file
src/impl/iThread/PosixWindows/PosixThread.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/PosixWindows/PosixThread.cpp.o
.PHONY : src/impl/iThread/PosixWindows/PosixThread.cpp.o

src/impl/iThread/PosixWindows/PosixThread.i: src/impl/iThread/PosixWindows/PosixThread.cpp.i

.PHONY : src/impl/iThread/PosixWindows/PosixThread.i

# target to preprocess a source file
src/impl/iThread/PosixWindows/PosixThread.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/PosixWindows/PosixThread.cpp.i
.PHONY : src/impl/iThread/PosixWindows/PosixThread.cpp.i

src/impl/iThread/PosixWindows/PosixThread.s: src/impl/iThread/PosixWindows/PosixThread.cpp.s

.PHONY : src/impl/iThread/PosixWindows/PosixThread.s

# target to generate assembly for a file
src/impl/iThread/PosixWindows/PosixThread.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/impl/iThread/PosixWindows/PosixThread.cpp.s
.PHONY : src/impl/iThread/PosixWindows/PosixThread.cpp.s

src/portable/JsonUtilities.o: src/portable/JsonUtilities.cpp.o

.PHONY : src/portable/JsonUtilities.o

# target to build an object file
src/portable/JsonUtilities.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/JsonUtilities.cpp.o
.PHONY : src/portable/JsonUtilities.cpp.o

src/portable/JsonUtilities.i: src/portable/JsonUtilities.cpp.i

.PHONY : src/portable/JsonUtilities.i

# target to preprocess a source file
src/portable/JsonUtilities.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/JsonUtilities.cpp.i
.PHONY : src/portable/JsonUtilities.cpp.i

src/portable/JsonUtilities.s: src/portable/JsonUtilities.cpp.s

.PHONY : src/portable/JsonUtilities.s

# target to generate assembly for a file
src/portable/JsonUtilities.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/JsonUtilities.cpp.s
.PHONY : src/portable/JsonUtilities.cpp.s

src/portable/Latch/Latch_test.o: src/portable/Latch/Latch_test.cpp.o

.PHONY : src/portable/Latch/Latch_test.o

# target to build an object file
src/portable/Latch/Latch_test.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/Latch/Latch_test.cpp.o
.PHONY : src/portable/Latch/Latch_test.cpp.o

src/portable/Latch/Latch_test.i: src/portable/Latch/Latch_test.cpp.i

.PHONY : src/portable/Latch/Latch_test.i

# target to preprocess a source file
src/portable/Latch/Latch_test.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/Latch/Latch_test.cpp.i
.PHONY : src/portable/Latch/Latch_test.cpp.i

src/portable/Latch/Latch_test.s: src/portable/Latch/Latch_test.cpp.s

.PHONY : src/portable/Latch/Latch_test.s

# target to generate assembly for a file
src/portable/Latch/Latch_test.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/Latch/Latch_test.cpp.s
.PHONY : src/portable/Latch/Latch_test.cpp.s

src/portable/MutexToken.o: src/portable/MutexToken.cpp.o

.PHONY : src/portable/MutexToken.o

# target to build an object file
src/portable/MutexToken.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/MutexToken.cpp.o
.PHONY : src/portable/MutexToken.cpp.o

src/portable/MutexToken.i: src/portable/MutexToken.cpp.i

.PHONY : src/portable/MutexToken.i

# target to preprocess a source file
src/portable/MutexToken.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/MutexToken.cpp.i
.PHONY : src/portable/MutexToken.cpp.i

src/portable/MutexToken.s: src/portable/MutexToken.cpp.s

.PHONY : src/portable/MutexToken.s

# target to generate assembly for a file
src/portable/MutexToken.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/MutexToken.cpp.s
.PHONY : src/portable/MutexToken.cpp.s

src/portable/PortableUtilityFunctions.o: src/portable/PortableUtilityFunctions.cpp.o

.PHONY : src/portable/PortableUtilityFunctions.o

# target to build an object file
src/portable/PortableUtilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/PortableUtilityFunctions.cpp.o
.PHONY : src/portable/PortableUtilityFunctions.cpp.o

src/portable/PortableUtilityFunctions.i: src/portable/PortableUtilityFunctions.cpp.i

.PHONY : src/portable/PortableUtilityFunctions.i

# target to preprocess a source file
src/portable/PortableUtilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/PortableUtilityFunctions.cpp.i
.PHONY : src/portable/PortableUtilityFunctions.cpp.i

src/portable/PortableUtilityFunctions.s: src/portable/PortableUtilityFunctions.cpp.s

.PHONY : src/portable/PortableUtilityFunctions.s

# target to generate assembly for a file
src/portable/PortableUtilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/PortableUtilityFunctions.cpp.s
.PHONY : src/portable/PortableUtilityFunctions.cpp.s

src/portable/ReferenceCounter.o: src/portable/ReferenceCounter.cpp.o

.PHONY : src/portable/ReferenceCounter.o

# target to build an object file
src/portable/ReferenceCounter.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/ReferenceCounter.cpp.o
.PHONY : src/portable/ReferenceCounter.cpp.o

src/portable/ReferenceCounter.i: src/portable/ReferenceCounter.cpp.i

.PHONY : src/portable/ReferenceCounter.i

# target to preprocess a source file
src/portable/ReferenceCounter.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/ReferenceCounter.cpp.i
.PHONY : src/portable/ReferenceCounter.cpp.i

src/portable/ReferenceCounter.s: src/portable/ReferenceCounter.cpp.s

.PHONY : src/portable/ReferenceCounter.s

# target to generate assembly for a file
src/portable/ReferenceCounter.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/ReferenceCounter.cpp.s
.PHONY : src/portable/ReferenceCounter.cpp.s

src/portable/SocketReader.o: src/portable/SocketReader.cpp.o

.PHONY : src/portable/SocketReader.o

# target to build an object file
src/portable/SocketReader.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/SocketReader.cpp.o
.PHONY : src/portable/SocketReader.cpp.o

src/portable/SocketReader.i: src/portable/SocketReader.cpp.i

.PHONY : src/portable/SocketReader.i

# target to preprocess a source file
src/portable/SocketReader.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/SocketReader.cpp.i
.PHONY : src/portable/SocketReader.cpp.i

src/portable/SocketReader.s: src/portable/SocketReader.cpp.s

.PHONY : src/portable/SocketReader.s

# target to generate assembly for a file
src/portable/SocketReader.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/SocketReader.cpp.s
.PHONY : src/portable/SocketReader.cpp.s

src/portable/base64/cdecode.o: src/portable/base64/cdecode.c.o

.PHONY : src/portable/base64/cdecode.o

# target to build an object file
src/portable/base64/cdecode.c.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/base64/cdecode.c.o
.PHONY : src/portable/base64/cdecode.c.o

src/portable/base64/cdecode.i: src/portable/base64/cdecode.c.i

.PHONY : src/portable/base64/cdecode.i

# target to preprocess a source file
src/portable/base64/cdecode.c.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/base64/cdecode.c.i
.PHONY : src/portable/base64/cdecode.c.i

src/portable/base64/cdecode.s: src/portable/base64/cdecode.c.s

.PHONY : src/portable/base64/cdecode.s

# target to generate assembly for a file
src/portable/base64/cdecode.c.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/base64/cdecode.c.s
.PHONY : src/portable/base64/cdecode.c.s

src/portable/base64/cencode.o: src/portable/base64/cencode.c.o

.PHONY : src/portable/base64/cencode.o

# target to build an object file
src/portable/base64/cencode.c.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/base64/cencode.c.o
.PHONY : src/portable/base64/cencode.c.o

src/portable/base64/cencode.i: src/portable/base64/cencode.c.i

.PHONY : src/portable/base64/cencode.i

# target to preprocess a source file
src/portable/base64/cencode.c.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/base64/cencode.c.i
.PHONY : src/portable/base64/cencode.c.i

src/portable/base64/cencode.s: src/portable/base64/cencode.c.s

.PHONY : src/portable/base64/cencode.s

# target to generate assembly for a file
src/portable/base64/cencode.c.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/base64/cencode.c.s
.PHONY : src/portable/base64/cencode.c.s

src/portable/iLogger/DomainLogger/DomainLogger.o: src/portable/iLogger/DomainLogger/DomainLogger.cpp.o

.PHONY : src/portable/iLogger/DomainLogger/DomainLogger.o

# target to build an object file
src/portable/iLogger/DomainLogger/DomainLogger.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/DomainLogger/DomainLogger.cpp.o
.PHONY : src/portable/iLogger/DomainLogger/DomainLogger.cpp.o

src/portable/iLogger/DomainLogger/DomainLogger.i: src/portable/iLogger/DomainLogger/DomainLogger.cpp.i

.PHONY : src/portable/iLogger/DomainLogger/DomainLogger.i

# target to preprocess a source file
src/portable/iLogger/DomainLogger/DomainLogger.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/DomainLogger/DomainLogger.cpp.i
.PHONY : src/portable/iLogger/DomainLogger/DomainLogger.cpp.i

src/portable/iLogger/DomainLogger/DomainLogger.s: src/portable/iLogger/DomainLogger/DomainLogger.cpp.s

.PHONY : src/portable/iLogger/DomainLogger/DomainLogger.s

# target to generate assembly for a file
src/portable/iLogger/DomainLogger/DomainLogger.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/DomainLogger/DomainLogger.cpp.s
.PHONY : src/portable/iLogger/DomainLogger/DomainLogger.cpp.s

src/portable/iLogger/LoggerCollection/LoggerCollection.o: src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.o

.PHONY : src/portable/iLogger/LoggerCollection/LoggerCollection.o

# target to build an object file
src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.o
.PHONY : src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.o

src/portable/iLogger/LoggerCollection/LoggerCollection.i: src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.i

.PHONY : src/portable/iLogger/LoggerCollection/LoggerCollection.i

# target to preprocess a source file
src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.i
.PHONY : src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.i

src/portable/iLogger/LoggerCollection/LoggerCollection.s: src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.s

.PHONY : src/portable/iLogger/LoggerCollection/LoggerCollection.s

# target to generate assembly for a file
src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.s
.PHONY : src/portable/iLogger/LoggerCollection/LoggerCollection.cpp.s

src/portable/iLogger/LoggerLatch/LoggerLatch.o: src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.o

.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch.o

# target to build an object file
src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.o
.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.o

src/portable/iLogger/LoggerLatch/LoggerLatch.i: src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.i

.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch.i

# target to preprocess a source file
src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.i
.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.i

src/portable/iLogger/LoggerLatch/LoggerLatch.s: src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.s

.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch.s

# target to generate assembly for a file
src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.s
.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch.cpp.s

src/portable/iLogger/LoggerLatch/LoggerLatch_test.o: src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.o

.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch_test.o

# target to build an object file
src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.o
.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.o

src/portable/iLogger/LoggerLatch/LoggerLatch_test.i: src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.i

.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch_test.i

# target to preprocess a source file
src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.i
.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.i

src/portable/iLogger/LoggerLatch/LoggerLatch_test.s: src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.s

.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch_test.s

# target to generate assembly for a file
src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.s
.PHONY : src/portable/iLogger/LoggerLatch/LoggerLatch_test.cpp.s

src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.o: src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.o

.PHONY : src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.o

# target to build an object file
src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.o
.PHONY : src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.o

src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.i: src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.i

.PHONY : src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.i

# target to preprocess a source file
src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.i
.PHONY : src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.i

src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.s: src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.s

.PHONY : src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.s

# target to generate assembly for a file
src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.s
.PHONY : src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.cpp.s

src/portable/iLogger/StandardOutLogger/StandardOutLogger.o: src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.o

.PHONY : src/portable/iLogger/StandardOutLogger/StandardOutLogger.o

# target to build an object file
src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.o:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.o
.PHONY : src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.o

src/portable/iLogger/StandardOutLogger/StandardOutLogger.i: src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.i

.PHONY : src/portable/iLogger/StandardOutLogger/StandardOutLogger.i

# target to preprocess a source file
src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.i:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.i
.PHONY : src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.i

src/portable/iLogger/StandardOutLogger/StandardOutLogger.s: src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.s

.PHONY : src/portable/iLogger/StandardOutLogger/StandardOutLogger.s

# target to generate assembly for a file
src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.s:
	$(MAKE) -f CMakeFiles/Utilities.dir/build.make CMakeFiles/Utilities.dir/src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.s
.PHONY : src/portable/iLogger/StandardOutLogger/StandardOutLogger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Utilities"
	@echo "... src/Utilities.o"
	@echo "... src/Utilities.i"
	@echo "... src/Utilities.s"
	@echo "... src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.o"
	@echo "... src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.i"
	@echo "... src/impl/UtilityFunctions/UnitTest/UnitTestUtilityFunctions.s"
	@echo "... src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.o"
	@echo "... src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.i"
	@echo "... src/impl/UtilityFunctions/Unix/UnixUtilityFunctions.s"
	@echo "... src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.o"
	@echo "... src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.i"
	@echo "... src/impl/UtilityFunctions/Windows/WindowsUtilityFunctions.s"
	@echo "... src/impl/iDirectory/GoogleMock/MockDirectory.o"
	@echo "... src/impl/iDirectory/GoogleMock/MockDirectory.i"
	@echo "... src/impl/iDirectory/GoogleMock/MockDirectory.s"
	@echo "... src/impl/iDirectory/Qt/QtDirectory.o"
	@echo "... src/impl/iDirectory/Qt/QtDirectory.i"
	@echo "... src/impl/iDirectory/Qt/QtDirectory.s"
	@echo "... src/impl/iDirectory/Unix/UnixDirectory.o"
	@echo "... src/impl/iDirectory/Unix/UnixDirectory.i"
	@echo "... src/impl/iDirectory/Unix/UnixDirectory.s"
	@echo "... src/impl/iLocation/locManagerGPS.o"
	@echo "... src/impl/iLocation/locManagerGPS.i"
	@echo "... src/impl/iLocation/locManagerGPS.s"
	@echo "... src/impl/iMutex/Appareo/AppareoMutex.o"
	@echo "... src/impl/iMutex/Appareo/AppareoMutex.i"
	@echo "... src/impl/iMutex/Appareo/AppareoMutex.s"
	@echo "... src/impl/iMutex/GoogleMock/MockMutex.o"
	@echo "... src/impl/iMutex/GoogleMock/MockMutex.i"
	@echo "... src/impl/iMutex/GoogleMock/MockMutex.s"
	@echo "... src/impl/iMutex/Posix/PosixMutex.o"
	@echo "... src/impl/iMutex/Posix/PosixMutex.i"
	@echo "... src/impl/iMutex/Posix/PosixMutex.s"
	@echo "... src/impl/iMutex/Windows/WindowsMutex.o"
	@echo "... src/impl/iMutex/Windows/WindowsMutex.i"
	@echo "... src/impl/iMutex/Windows/WindowsMutex.s"
	@echo "... src/impl/iTCPServer/Gateway/GatewayTCPServer.o"
	@echo "... src/impl/iTCPServer/Gateway/GatewayTCPServer.i"
	@echo "... src/impl/iTCPServer/Gateway/GatewayTCPServer.s"
	@echo "... src/impl/iTCPSocket/Gateway/GatewayTCPSocket.o"
	@echo "... src/impl/iTCPSocket/Gateway/GatewayTCPSocket.i"
	@echo "... src/impl/iTCPSocket/Gateway/GatewayTCPSocket.s"
	@echo "... src/impl/iTCPSocket/GoogleMock/MockTCPSocket.o"
	@echo "... src/impl/iTCPSocket/GoogleMock/MockTCPSocket.i"
	@echo "... src/impl/iTCPSocket/GoogleMock/MockTCPSocket.s"
	@echo "... src/impl/iThread/Appareo/AppareoThread.o"
	@echo "... src/impl/iThread/Appareo/AppareoThread.i"
	@echo "... src/impl/iThread/Appareo/AppareoThread.s"
	@echo "... src/impl/iThread/Posix/PosixThread.o"
	@echo "... src/impl/iThread/Posix/PosixThread.i"
	@echo "... src/impl/iThread/Posix/PosixThread.s"
	@echo "... src/impl/iThread/PosixWindows/PosixThread.o"
	@echo "... src/impl/iThread/PosixWindows/PosixThread.i"
	@echo "... src/impl/iThread/PosixWindows/PosixThread.s"
	@echo "... src/portable/JsonUtilities.o"
	@echo "... src/portable/JsonUtilities.i"
	@echo "... src/portable/JsonUtilities.s"
	@echo "... src/portable/Latch/Latch_test.o"
	@echo "... src/portable/Latch/Latch_test.i"
	@echo "... src/portable/Latch/Latch_test.s"
	@echo "... src/portable/MutexToken.o"
	@echo "... src/portable/MutexToken.i"
	@echo "... src/portable/MutexToken.s"
	@echo "... src/portable/PortableUtilityFunctions.o"
	@echo "... src/portable/PortableUtilityFunctions.i"
	@echo "... src/portable/PortableUtilityFunctions.s"
	@echo "... src/portable/ReferenceCounter.o"
	@echo "... src/portable/ReferenceCounter.i"
	@echo "... src/portable/ReferenceCounter.s"
	@echo "... src/portable/SocketReader.o"
	@echo "... src/portable/SocketReader.i"
	@echo "... src/portable/SocketReader.s"
	@echo "... src/portable/base64/cdecode.o"
	@echo "... src/portable/base64/cdecode.i"
	@echo "... src/portable/base64/cdecode.s"
	@echo "... src/portable/base64/cencode.o"
	@echo "... src/portable/base64/cencode.i"
	@echo "... src/portable/base64/cencode.s"
	@echo "... src/portable/iLogger/DomainLogger/DomainLogger.o"
	@echo "... src/portable/iLogger/DomainLogger/DomainLogger.i"
	@echo "... src/portable/iLogger/DomainLogger/DomainLogger.s"
	@echo "... src/portable/iLogger/LoggerCollection/LoggerCollection.o"
	@echo "... src/portable/iLogger/LoggerCollection/LoggerCollection.i"
	@echo "... src/portable/iLogger/LoggerCollection/LoggerCollection.s"
	@echo "... src/portable/iLogger/LoggerLatch/LoggerLatch.o"
	@echo "... src/portable/iLogger/LoggerLatch/LoggerLatch.i"
	@echo "... src/portable/iLogger/LoggerLatch/LoggerLatch.s"
	@echo "... src/portable/iLogger/LoggerLatch/LoggerLatch_test.o"
	@echo "... src/portable/iLogger/LoggerLatch/LoggerLatch_test.i"
	@echo "... src/portable/iLogger/LoggerLatch/LoggerLatch_test.s"
	@echo "... src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.o"
	@echo "... src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.i"
	@echo "... src/portable/iLogger/RollingAppenderDirectoryLogger/RollingAppenderDirectoryLogger.s"
	@echo "... src/portable/iLogger/StandardOutLogger/StandardOutLogger.o"
	@echo "... src/portable/iLogger/StandardOutLogger/StandardOutLogger.i"
	@echo "... src/portable/iLogger/StandardOutLogger/StandardOutLogger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

